# Generated by Django 5.2.1 on 2025-06-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
