# Generated by Django 5.2.1 on 2025-06-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_flix_app', '0002_userwatchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='videos/%(height)sp/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='video_flix_app.video')),
            ],
        ),
    ]
