# Generated by Django 5.2.1 on 2025-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_flix_app', '0005_alter_video_thumbnail_alter_videoresolution_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
