# Generated by Django 5.2.1 on 2025-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_flix_app', '0007_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='VideoResolution',
        ),
    ]
