# Generated by Django 5.2.1 on 2025-06-25 18:09

import video_flix_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_flix_app', '0008_video_hls_playlist_delete_videoresolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=video_flix_app.models.video_file_upload_to),
        ),
    ]
